#
# BoardConfig.mk - Samsung Galaxy A31 (a31, SM-A315F, MT6768)
# "VERIFY" olan her deger stock cihazdan okunmali, tahmin.
#

DEVICE_PATH := device/samsung/a31

# Allow missing dependencies (bring-up icin, sonra kaldir)
ALLOW_MISSING_DEPENDENCIES := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a75

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

# Platform
TARGET_BOARD_PLATFORM := mt6768
TARGET_BOOTLOADER_BOARD_NAME := mt6768
TARGET_NO_BOOTLOADER := true
BOARD_HAS_MTK_HARDWARE := true
MTK_HARDWARE := true

# Shipping API (A31 Android 10 ile cikti)
PRODUCT_SHIPPING_API_LEVEL := 29

# Kernel - Samsung SM-A315F kaynagi (begonia mt6785 kernel'i boot etmez)
BOARD_KERNEL_IMAGE_NAME := Image.gz
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x11a88000
BOARD_KERNEL_TAGS_OFFSET := 0x07c08000
BOARD_DTB_OFFSET := 0x07c08000
BOARD_SECOND_OFFSET := 0x00000000
BOARD_BOOT_HEADER_VERSION := 2

BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2
BOARD_KERNEL_CMDLINE += androidboot.hardware=mt6768
BOARD_KERNEL_CMDLINE += androidboot.selinux=permissive # bring-up sonrasi sil

BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_MKBOOTIMG_ARGS += --second_offset $(BOARD_SECOND_OFFSET)

TARGET_KERNEL_SOURCE := kernel/samsung/mt6768
TARGET_KERNEL_CONFIG := a31_defconfig
TARGET_KERNEL_CLANG_COMPILE := true
TARGET_KERNEL_ADDITIONAL_FLAGS := LD=ld.lld

# Hizli bring-up icin prebuilt kernel kullanmak istersen:
# TARGET_FORCE_PREBUILT_KERNEL := true
# TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image.gz
# BOARD_PREBUILT_DTBIMAGE_DIR := $(DEVICE_PATH)/prebuilt/dtb
# Panel (EA8074 / S6E3HA3) secimi cmdline ile degil, kernel DTS + dtbo ile yapilir.
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/dtbo.img
BOARD_INCLUDE_RECOVERY_DTBO := true

# Partitions - dynamic (super), A-only
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_BOOTIMAGE_PARTITION_SIZE := 33554432          # VERIFY
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 67108864      # VERIFY
BOARD_DTBOIMG_PARTITION_SIZE := 8388608             # VERIFY
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4

BOARD_SUPER_PARTITION_SIZE := 5368709120            # VERIFY: blockdev --getsize64 super
BOARD_SUPER_PARTITION_GROUPS := a31_dynamic_partitions
BOARD_A31_DYNAMIC_PARTITIONS_PARTITION_LIST := system system_ext product vendor odm
BOARD_A31_DYNAMIC_PARTITIONS_SIZE := 5364514816     # super - 4MB

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4

TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_ODM := odm

BOARD_ROOT_EXTRA_FOLDERS := efs carrier cache
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# AVB
BOARD_AVB_ENABLE := false
BOARD_BUILD_DISABLED_VBMETAIMAGE := true

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/etc/fstab.mt6768
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_USES_RECOVERY_AS_BOOT := false
TARGET_NO_RECOVERY := false

# Display
TARGET_SCREEN_DENSITY := 420
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2400

# VNDK / VINTF - stock vendor ile uyumlu olmali
BOARD_VNDK_VERSION := current
PRODUCT_FULL_TREBLE_OVERRIDE := true
DEVICE_MANIFEST_FILE := $(DEVICE_PATH)/vintf/manifest.xml         # stock vendor/etc/vintf'ten
DEVICE_MATRIX_FILE := $(DEVICE_PATH)/vintf/compatibility_matrix.xml
DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE += $(DEVICE_PATH)/vintf/framework_compatibility_matrix.xml
BUILD_BROKEN_VINTF_PRODUCT_COPY_FILES := true

# Graphics
TARGET_USES_HWC2 := true
TARGET_USES_ION := true
BOARD_USES_MTK_HARDWARE := true
USE_OPENGL_RENDERER := true
BOARD_EGL_CFG := $(DEVICE_PATH)/configs/egl.cfg
TARGET_HAS_NO_WLAN_STATS := true

# Camera - stock vendor/odm HAL kullanilir
TARGET_USES_MTK_CAMERA := true
TARGET_HAS_LEGACY_CAMERA_HAL1 := false

# Audio / Bluetooth / WiFi
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_MTK := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := $(DEVICE_PATH)/bluetooth
WPA_SUPPLICANT_VERSION := VER_0_8_X
BOARD_WLAN_DEVICE := MediaTek
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
WIFI_DRIVER_FW_PATH_PARAM := /dev/wmtWifi
WIFI_DRIVER_STATE_CTRL_PARAM := /dev/wmtWifi
WIFI_DRIVER_STATE_ON := 1
WIFI_DRIVER_STATE_OFF := 0

# Sepolicy
include device/mediatek/sepolicy_vndr/SEPolicy.mk
BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor
SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/private

# Properties
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop

# Inherit proprietary
include vendor/samsung/a31/BoardConfigVendor.mk
